/**
 * generated by Xtext
 */
package tp5.dslexterno.xtext.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class PlanificacionMateriasQuickfixProvider extends XbaseQuickfixProvider {
}
