/*
* generated by Xtext
*/
package tp5.dslexterno.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tp5.dslexterno.xtext.services.PlanificacionMateriasGrammarAccess;

public class PlanificacionMateriasParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PlanificacionMateriasGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected tp5.dslexterno.xtext.parser.antlr.internal.InternalPlanificacionMateriasParser createParser(XtextTokenStream stream) {
		return new tp5.dslexterno.xtext.parser.antlr.internal.InternalPlanificacionMateriasParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PlanificacionMateriasGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlanificacionMateriasGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
