/*
* generated by Xtext
*/
package tp5.dslexterno.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PlanificacionMateriasAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("tp5/dslexterno/xtext/parser/antlr/internal/InternalPlanificacionMaterias.tokens");
	}
}
