/**
 * generated by Xtext
 */
package tp5.dslexterno.xtext.ui.contentassist;

import tp5.dslexterno.xtext.ui.contentassist.AbstractPlanificacionMateriasProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PlanificacionMateriasProposalProvider extends AbstractPlanificacionMateriasProposalProvider {
}
