/*
* generated by Xtext
*/
package tp5.dslexterno.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PlanificacionMateriasUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return tp5.dslexterno.xtext.ui.internal.PlanificacionMateriasActivator.getInstance().getInjector("tp5.dslexterno.xtext.PlanificacionMaterias");
	}
	
}
