/*
* generated by Xtext
*/
package tp5.dslexterno.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PlanificacionMateriasStandaloneSetup extends PlanificacionMateriasStandaloneSetupGenerated{

	public static void doSetup() {
		new PlanificacionMateriasStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

