/*
 * generated by Xtext
 */
package tp5.dslexterno.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlanificacionMateriasRuntimeModule extends tp5.dslexterno.xtext.AbstractPlanificacionMateriasRuntimeModule {

}
