/*
 * generated by Xtext
 */
package tp5.dslexterno.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import tp5.dslexterno.xtext.ui.internal.PlanificacionMateriasActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlanificacionMateriasExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlanificacionMateriasActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlanificacionMateriasActivator.getInstance().getInjector(PlanificacionMateriasActivator.TP5_DSLEXTERNO_XTEXT_PLANIFICACIONMATERIAS);
	}
	
}
