/*
 * generated by Xtext
 */
package tp5.dslexterno.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlanificacionMateriasUiModule extends tp5.dslexterno.xtext.ui.AbstractPlanificacionMateriasUiModule {
	public PlanificacionMateriasUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
